### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by The-Daishogun** [Noyan1997/github-profile-viewer#2]
when building the project I encountered the following issues:

```
yarn build
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[=   ] info  - Generating static pages (0/5)TypeError: Cannot read properties of undefined (reading 'message')
    at UserName (/tmp/github-profile-viewer/.next/server/chunks/738.js:391:15)
    at Wc (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)

Error occurred prerendering page "/profile". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'message')
    at UserName (/tmp/github-profile-viewer/.next/server/chunks/738.js:391:15)
    at Wc (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/tmp/github-profile-viewer/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
info  - Generating static pages (5/5)

> Build error occurred
Error: Export encountered errors on following paths:
        /profile
    at /tmp/github-profile-viewer/node_modules/next/dist/export/index.js:395:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/tmp/github-profile-viewer/node_modules/next/dist/trace/trace.js:79:20)
    at async /tmp/github-profile-viewer/node_modules/next/dist/build/index.js:1094:21
    at async Span.traceAsyncFn (/tmp/github-profile-viewer/node_modules/next/dist/trace/trace.js:79:20)
    at async /tmp/github-profile-viewer/node_modules/next/dist/build/index.js:971:17
    at async Span.traceAsyncFn (/tmp/github-profile-viewer/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/tmp/github-profile-viewer/node_modules/next/dist/build/index.js:64:29)
```

**Comment by Noyan1997** [comment]
This problem is solved, please test again

**Comment by The-Daishogun** [comment]
Thanks for the fix

**Comment by Noyan1997** [comment]
Hi Dear Mohammad;
Hope you are doing great, Due to the task response and the interview
result, I'm interested to hear your comments on my assignment. It would
have a high impact to know more about my weaknesses, so then I can improve
my skills. If you can help me with that, I would appreciate you a lot.
Wish all the bests for you and the Quera Team!
Sincerely
Noyan
